"""initial_schema_with_zuultimate_tenant_id

Revision ID: 37acb56fb5a0
Revises: 
Create Date: 2026-02-24 11:54:57.204629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37acb56fb5a0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('zuultimate_tenant_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_tenants_zuultimate_tenant_id'), 'tenants', ['zuultimate_tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_zuultimate_tenant_id'), table_name='tenants')
    op.drop_column('tenants', 'zuultimate_tenant_id')
    # ### end Alembic commands ###
